server:
  port: 9000

spring:
  application:
    name: "card"
  profiles:
    active: "production"
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: #example
    password: #example
  jpa:
    show-sql: true
  sql:
    init:
      mode: "always"
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/

info:
  app:
    name: "card"
    description: "Card Microservice"
    version: "1.0.0"

logging:
  level:
    com:
      marjoz:
        card: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"