services:
  network-deploy-service:
    networks:
      - marjoz

  microservice-database-config:
    extends:
      service: network-deploy-service
    image: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: #example

  microservice-base-configuration:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-configserver-configuration:
    extends:
      service: microservice-base-configuration
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIGURATION_IMPORT: configserver:http://configserver:8071/
      SPRING_DATASOURCE_USERNAME: #example
      SPRING_DATASOURCE_PASSWORD: #example

  microservice-servicediscovery-configuration:
    extends:
      service: microservice-configserver-configuration
    depends_on:
      servicediscovery:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servicediscovery:8761/eureka
